services:
#  quarkus-app:
#    build:
#      context: .
#      dockerfile: ./src/main/docker/Dockerfile.jvm
#    ports:
#      - 8080:8080
#    depends_on:
#      - sqlserver.configurator
#    env_file:
#      - .env
#    networks:
#      - default-network
  mssqldb:
    container_name: mssqldb22
    hostname: mssqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .env
    ports:
      - ${MSSQL_TCP_PORT}:1433
    volumes:
      - mssql-data:/var/opt/mssql/
      - mssql-data:/var/opt/sqlserver/data
      - mssql-data:/var/opt/sqlserver/log
      - mssql-data:/var/opt/sqlserver/backup
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S $$DATABASE_HOST,$$MSSQL_TCP_PORT -U sa -P $$SA_PASSWORD -Q 'SELECT 1'"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 2s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    depends_on:
      mssqldb:
        condition: service_healthy
    env_file:
      - .env
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S $$DATABASE_HOST,$$MSSQL_TCP_PORT -U sa -P $$SA_PASSWORD -d master -i docker-entrypoint-initdb.d/init.sql -C;
      echo "All done!";
      '
    networks:
      - default-network

volumes:
  mssql-data:

networks:
  default-network:
    driver: bridge